'*.{ts,tsx,js}':
  - 'eslint --cache --cache-location ./node_modules/.cache/.eslintcache --fix'
  - 'prettier --loglevel warn --cache --write'
'*.scss':
  - 'stylelint --cache --cache-location ./node_modules/.cache/.stylelintchache --fix'
  - 'prettier --loglevel warn --cache --write'
'*.{json,yml,scss}': 'prettier --loglevel warn --cache --write'
